---
AllCops:
  Exclude:
    - compile-extensions/**/*
    - vendor/**/*
    - spec/**/*
  TargetRubyVersion:
    2.3.1
Documentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 18
ParameterLists:
  Max: 9
Metrics/AbcSize:
  Max: 30
ClassLength:
  Max: 150
Style/FrozenStringLiteralComment:
  Enabled: false
